//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdate.Demo.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DllInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DllInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TempNameField;
        
        private System.DateTime ModifiedTimeField;
        
        private AutoUpdate.Demo.ServiceReference.DllStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TempName {
            get {
                return this.TempNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TempNameField, value) != true)) {
                    this.TempNameField = value;
                    this.RaisePropertyChanged("TempName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime ModifiedTime {
            get {
                return this.ModifiedTimeField;
            }
            set {
                if ((this.ModifiedTimeField.Equals(value) != true)) {
                    this.ModifiedTimeField = value;
                    this.RaisePropertyChanged("ModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public AutoUpdate.Demo.ServiceReference.DllStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DllStatus", Namespace="http://tempuri.org/")]
    public enum DllStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsNewest = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NeedUpdate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoFile = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.AutoUpdateServiceSoap")]
    public interface AutoUpdateServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dllInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVersion", ReplyAction="*")]
        AutoUpdate.Demo.ServiceReference.CheckVersionResponse CheckVersion(AutoUpdate.Demo.ServiceReference.CheckVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.CheckVersionResponse> CheckVersionAsync(AutoUpdate.Demo.ServiceReference.CheckVersionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dllList 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVersions", ReplyAction="*")]
        AutoUpdate.Demo.ServiceReference.CheckVersionsResponse CheckVersions(AutoUpdate.Demo.ServiceReference.CheckVersionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVersions", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.CheckVersionsResponse> CheckVersionsAsync(AutoUpdate.Demo.ServiceReference.CheckVersionsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dllInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        AutoUpdate.Demo.ServiceReference.UpdateResponse Update(AutoUpdate.Demo.ServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.UpdateResponse> UpdateAsync(AutoUpdate.Demo.ServiceReference.UpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dllList 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateList", ReplyAction="*")]
        AutoUpdate.Demo.ServiceReference.UpdateListResponse UpdateList(AutoUpdate.Demo.ServiceReference.UpdateListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateList", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.UpdateListResponse> UpdateListAsync(AutoUpdate.Demo.ServiceReference.UpdateListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckVersion", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.CheckVersionRequestBody Body;
        
        public CheckVersionRequest() {
        }
        
        public CheckVersionRequest(AutoUpdate.Demo.ServiceReference.CheckVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo dllInfo;
        
        public CheckVersionRequestBody() {
        }
        
        public CheckVersionRequestBody(AutoUpdate.Demo.ServiceReference.DllInfo dllInfo) {
            this.dllInfo = dllInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.CheckVersionResponseBody Body;
        
        public CheckVersionResponse() {
        }
        
        public CheckVersionResponse(AutoUpdate.Demo.ServiceReference.CheckVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo CheckVersionResult;
        
        public CheckVersionResponseBody() {
        }
        
        public CheckVersionResponseBody(AutoUpdate.Demo.ServiceReference.DllInfo CheckVersionResult) {
            this.CheckVersionResult = CheckVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVersionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckVersions", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.CheckVersionsRequestBody Body;
        
        public CheckVersionsRequest() {
        }
        
        public CheckVersionsRequest(AutoUpdate.Demo.ServiceReference.CheckVersionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckVersionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo[] dllList;
        
        public CheckVersionsRequestBody() {
        }
        
        public CheckVersionsRequestBody(AutoUpdate.Demo.ServiceReference.DllInfo[] dllList) {
            this.dllList = dllList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVersionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckVersionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.CheckVersionsResponseBody Body;
        
        public CheckVersionsResponse() {
        }
        
        public CheckVersionsResponse(AutoUpdate.Demo.ServiceReference.CheckVersionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckVersionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo[] CheckVersionsResult;
        
        public CheckVersionsResponseBody() {
        }
        
        public CheckVersionsResponseBody(AutoUpdate.Demo.ServiceReference.DllInfo[] CheckVersionsResult) {
            this.CheckVersionsResult = CheckVersionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(AutoUpdate.Demo.ServiceReference.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo dllInfo;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(AutoUpdate.Demo.ServiceReference.DllInfo dllInfo) {
            this.dllInfo = dllInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(AutoUpdate.Demo.ServiceReference.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(AutoUpdate.Demo.ServiceReference.DllInfo UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateList", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.UpdateListRequestBody Body;
        
        public UpdateListRequest() {
        }
        
        public UpdateListRequest(AutoUpdate.Demo.ServiceReference.UpdateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo[] dllList;
        
        public UpdateListRequestBody() {
        }
        
        public UpdateListRequestBody(AutoUpdate.Demo.ServiceReference.DllInfo[] dllList) {
            this.dllList = dllList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoUpdate.Demo.ServiceReference.UpdateListResponseBody Body;
        
        public UpdateListResponse() {
        }
        
        public UpdateListResponse(AutoUpdate.Demo.ServiceReference.UpdateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoUpdate.Demo.ServiceReference.DllInfo[] UpdateListResult;
        
        public UpdateListResponseBody() {
        }
        
        public UpdateListResponseBody(AutoUpdate.Demo.ServiceReference.DllInfo[] UpdateListResult) {
            this.UpdateListResult = UpdateListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoUpdateServiceSoapChannel : AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoUpdateServiceSoapClient : System.ServiceModel.ClientBase<AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap>, AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap {
        
        public AutoUpdateServiceSoapClient() {
        }
        
        public AutoUpdateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoUpdateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoUpdateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoUpdateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoUpdate.Demo.ServiceReference.CheckVersionResponse AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.CheckVersion(AutoUpdate.Demo.ServiceReference.CheckVersionRequest request) {
            return base.Channel.CheckVersion(request);
        }
        
        public AutoUpdate.Demo.ServiceReference.DllInfo CheckVersion(AutoUpdate.Demo.ServiceReference.DllInfo dllInfo) {
            AutoUpdate.Demo.ServiceReference.CheckVersionRequest inValue = new AutoUpdate.Demo.ServiceReference.CheckVersionRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.CheckVersionRequestBody();
            inValue.Body.dllInfo = dllInfo;
            AutoUpdate.Demo.ServiceReference.CheckVersionResponse retVal = ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).CheckVersion(inValue);
            return retVal.Body.CheckVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.CheckVersionResponse> AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.CheckVersionAsync(AutoUpdate.Demo.ServiceReference.CheckVersionRequest request) {
            return base.Channel.CheckVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.CheckVersionResponse> CheckVersionAsync(AutoUpdate.Demo.ServiceReference.DllInfo dllInfo) {
            AutoUpdate.Demo.ServiceReference.CheckVersionRequest inValue = new AutoUpdate.Demo.ServiceReference.CheckVersionRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.CheckVersionRequestBody();
            inValue.Body.dllInfo = dllInfo;
            return ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).CheckVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoUpdate.Demo.ServiceReference.CheckVersionsResponse AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.CheckVersions(AutoUpdate.Demo.ServiceReference.CheckVersionsRequest request) {
            return base.Channel.CheckVersions(request);
        }
        
        public AutoUpdate.Demo.ServiceReference.DllInfo[] CheckVersions(AutoUpdate.Demo.ServiceReference.DllInfo[] dllList) {
            AutoUpdate.Demo.ServiceReference.CheckVersionsRequest inValue = new AutoUpdate.Demo.ServiceReference.CheckVersionsRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.CheckVersionsRequestBody();
            inValue.Body.dllList = dllList;
            AutoUpdate.Demo.ServiceReference.CheckVersionsResponse retVal = ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).CheckVersions(inValue);
            return retVal.Body.CheckVersionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.CheckVersionsResponse> AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.CheckVersionsAsync(AutoUpdate.Demo.ServiceReference.CheckVersionsRequest request) {
            return base.Channel.CheckVersionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.CheckVersionsResponse> CheckVersionsAsync(AutoUpdate.Demo.ServiceReference.DllInfo[] dllList) {
            AutoUpdate.Demo.ServiceReference.CheckVersionsRequest inValue = new AutoUpdate.Demo.ServiceReference.CheckVersionsRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.CheckVersionsRequestBody();
            inValue.Body.dllList = dllList;
            return ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).CheckVersionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoUpdate.Demo.ServiceReference.UpdateResponse AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.Update(AutoUpdate.Demo.ServiceReference.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public AutoUpdate.Demo.ServiceReference.DllInfo Update(AutoUpdate.Demo.ServiceReference.DllInfo dllInfo) {
            AutoUpdate.Demo.ServiceReference.UpdateRequest inValue = new AutoUpdate.Demo.ServiceReference.UpdateRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.UpdateRequestBody();
            inValue.Body.dllInfo = dllInfo;
            AutoUpdate.Demo.ServiceReference.UpdateResponse retVal = ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.UpdateResponse> AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.UpdateAsync(AutoUpdate.Demo.ServiceReference.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.UpdateResponse> UpdateAsync(AutoUpdate.Demo.ServiceReference.DllInfo dllInfo) {
            AutoUpdate.Demo.ServiceReference.UpdateRequest inValue = new AutoUpdate.Demo.ServiceReference.UpdateRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.UpdateRequestBody();
            inValue.Body.dllInfo = dllInfo;
            return ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoUpdate.Demo.ServiceReference.UpdateListResponse AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.UpdateList(AutoUpdate.Demo.ServiceReference.UpdateListRequest request) {
            return base.Channel.UpdateList(request);
        }
        
        public AutoUpdate.Demo.ServiceReference.DllInfo[] UpdateList(AutoUpdate.Demo.ServiceReference.DllInfo[] dllList) {
            AutoUpdate.Demo.ServiceReference.UpdateListRequest inValue = new AutoUpdate.Demo.ServiceReference.UpdateListRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.UpdateListRequestBody();
            inValue.Body.dllList = dllList;
            AutoUpdate.Demo.ServiceReference.UpdateListResponse retVal = ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).UpdateList(inValue);
            return retVal.Body.UpdateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.UpdateListResponse> AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap.UpdateListAsync(AutoUpdate.Demo.ServiceReference.UpdateListRequest request) {
            return base.Channel.UpdateListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoUpdate.Demo.ServiceReference.UpdateListResponse> UpdateListAsync(AutoUpdate.Demo.ServiceReference.DllInfo[] dllList) {
            AutoUpdate.Demo.ServiceReference.UpdateListRequest inValue = new AutoUpdate.Demo.ServiceReference.UpdateListRequest();
            inValue.Body = new AutoUpdate.Demo.ServiceReference.UpdateListRequestBody();
            inValue.Body.dllList = dllList;
            return ((AutoUpdate.Demo.ServiceReference.AutoUpdateServiceSoap)(this)).UpdateListAsync(inValue);
        }
    }
}
